new example 010
ansys/pyprimemesh pull request #626
Opened 2023-10-19 07:13 UTC by agvarghe

2023-10-24 14:33 UTC, waltersma commented on src/ansys/meshing/prime/examples/examples.py
> +    >>>         _ = io.read_cad(f1_rw_drs, params=prime.FileReadParams(model))
Hi @agvarghe, I think you need to modify this line as this should be import_cad and has associated params.  Same again for similar instances below.

2023-10-24 14:34 UTC, waltersma commented on src/ansys/meshing/prime/examples/examples.py
> +    >>>         _ = io.import_cad(block_model, params=prime.FileReadParams(model))
Hi @agvarghe, params not defined correctly.

2023-10-24 14:35 UTC, waltersma requested changes
examples need fixing.

2023-10-25 07:31 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +mesh_util.read(file_name=prime.examples.download_block_model_scdoc())
@agvarghe this needs to be fmd or pmdat for running in a container as the SpaceClaim out of process option will not be available in this environment.

2023-10-26 09:46 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +The objective is to illustrate the process of exporting mesh files into a variety of
@agvarghe objective is to illustrate how data is converted and passed during import and export of mesh and geometry?

2023-10-26 09:47 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +* Import the CAD geometry file for the solid block.
@agvarghe Import CAD geometry and review the imported entities

2023-10-26 09:49 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +* Export the mesh file as pmdat, cdb and cas format.
@agvarghe + Review the entities to be exported to solvers.

2023-10-26 09:50 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +* Import the mesh file.
@agvarghe Import the created solver files to review the entities as they are coming from the solvers.

2023-10-26 09:52 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +# The topology data is preserved in the part when created from a cad file.
@agvarghe explain what is there in SCDM and how this corresponds to the entities in Prime

2023-10-26 09:53 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +# Named Selections present in the CAD are imported as labels. In this case, the Named Selection
@agvarghe should we define this as "Named selections or groups"

2023-10-26 09:54 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +# present in the CAD **my_group** is imported as a label.
@agvarghe lets add both an edge group and a volume group and show these in this example

2023-10-26 09:57 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +# The bodies present in the CAD are imported as Volume Zones,  in this case the body **solid** is
@agvarghe lets define Zones, "a collection of either topo or zonelet entities that we can assign properties to in a solver when exported as mesh".  and an example such as "if we wish to assign a material to a region of the model we can define a volume zone for multiple topo volumes or cell zonelets so we can apply the property".

2023-10-26 09:58 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +mesh_util.read(file_name=prime.examples.download_block_model_fmd())
@agvarghe add a commented line here to show reading the scdoc if windows OS and Ansys install is available

2023-10-26 10:14 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +# The topology data is preserved in the part when created from a cad file.
in PyPrimeMesh we have a single topo part with 1 topo volume, x topo faces and y topo edges.  These entities correspond to SCDM....
A Volume zone is also defined for the topovolume for the solid body.

2023-10-26 10:15 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +# The topo faces consists of geom zonelets and mesh zonelets,
@agvarghe the topo part currently has no mesh associated with it and contains only geometry.

2023-10-26 10:17 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +# Using Lucid api, User can generate a conformal mesh , this is called meshed zonelets.
meshed zonelets are only available once the topo part is converted to a mesh part by deleting the topo entities.

2023-11-13 16:49 UTC, waltersma requested changes

2023-11-13 16:49 UTC, waltersma commented on doc/source/images/00_after_cad_import.png
@agvarghe please review the numbers of entities in these images as they look incorrect.  Topoedges seem to be confused with topofaces.

2023-11-16 06:18 UTC, agvarghe commented on doc/source/images/00_after_cad_import.png
Thanks, i have fixed this in the latest commit

2023-11-20 00:08 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +#   PyPrimeMesh.
```suggestion
# * TopoEdge represent the curves/edges present in the CAD.
#   In this case there are **17 edges** present in SpaceClaim are imported
#   as **17 TopoEdges**.
#
# * TopoFace represent the surfaces/faces present in the CAD.
#   The **8 CAD Faces** present in SpaceClaim are imported as **8 Topofaces** in
#   PyPrimeMesh.
```

2023-11-20 00:50 UTC, waltersma commented
@ninad-kamat @agvarghe for the cdb import we may want to delay this part of the example until this issue is resolved.

2023-11-20 05:18 UTC, agvarghe commented
> @ninad-kamat @agvarghe for the cdb import we may want to delay this part of the example until this issue is resolved.

sure, i will modify the file and remove the section talking about cdb import

2023-11-27 10:58 UTC, waltersma commented on examples/gallery/00_lucid_file_IO.py
> +# Export mesh  as PyPrimeMesh (.pmdat) native format mesh file
```suggestion
# Export mesh as PyPrimeMesh (.pmdat) native format mesh file
```

2023-11-29 11:25 UTC, merged