Feat/adapt common plotter
ansys/pyprimemesh pull request #806
Opened 2024-05-28 07:49 UTC by AlejandroFernandezLuces

2024-05-31 06:41 UTC, RobPasMue requested changes
Some global changes requested from my side. Feel free to initiate a discussion on them :)

2024-05-31 06:41 UTC, RobPasMue commented on doc/source/conf.py
> +os.environ["PYANSYS_VISUALIZER_DOC_MODE"] = "true"
```suggestion
import ansys.tools.visualization_interface as viz_interface

viz_interface.DOCUMENTATION_BUILD = True
```

2024-05-31 06:41 UTC, RobPasMue commented on doc/source/user_guide/graphics.rst
> +    >>> display.show()
Can't we come up with a wrapper ``display(**kwargs)`` function that wraps these three calls around? That way you don't break that much the old API...

2024-05-31 06:41 UTC, RobPasMue commented on doc/source/user_guide/graphics.rst
> +    >>> display.show()
This applies for the entire codebase.

2024-05-31 06:41 UTC, RobPasMue commented on .github/workflows/ci_cd.yml
> +  PYANSYS_VISUALIZER_TESTMODE: true
Don't they have a conftest.py where we could define this behavior? I am tempted of changing it as well on other repos as well...

2024-05-31 06:41 UTC, RobPasMue commented on src/ansys/meshing/prime/core/mesh.py
> +from beartype.typing import Dict, List, Union
Wait a second... are they using ``beartype``? If not, you have to switch to the ``typing`` module.

2024-05-31 06:41 UTC, RobPasMue commented on src/ansys/meshing/prime/core/mesh.py
> +            _description_
Descriptions are needed.

2024-05-31 06:41 UTC, RobPasMue commented on src/ansys/meshing/prime/core/mesh.py
> +
Same here... please review the codebase

2024-05-31 06:41 UTC, RobPasMue commented on src/ansys/meshing/prime/graphics/plotter.py
> +from beartype.typing import Any, Dict, List, Optional
Same issue here

2024-05-31 06:41 UTC, RobPasMue commented on src/ansys/meshing/prime/graphics/plotter.py
> +        """
Missing docstring definitions

2024-05-31 06:41 UTC, RobPasMue commented on src/ansys/meshing/prime/graphics/widgets/images/show_ruler.png
Is this one needed? I thought it comes by default with the viz interface

2024-05-31 09:43 UTC, AlejandroFernandezLuces commented on src/ansys/meshing/prime/graphics/widgets/images/show_ruler.png
Nope, this one is custom for PyPrime. I think it can be added to the vizualization interface though, but do other libraries need this feature? I would prefer to avoid cluttering of the GUI as much as possible

2024-05-31 10:26 UTC, AlejandroFernandezLuces commented on doc/source/user_guide/graphics.rst
> +    >>> display.show()
The current API calls directy the object to show the plotter, rather than calling a method:

```python
display = Graphics(model)
display()
```

This is something I've been wanting to change for a while, I think this is not an intuitive way to use the plotter. 
Another issue with this is they could make changes to the Model and keep plotting different things in the plotter:

```python
for part_name in coarse_wrap:
    # Each open part before wrap
    display(scope=prime.ScopeDefinition(model, part_expression=part_name))
    closed_part = mesh_util.wrap(
        input_parts=part_name,
        max_size=coarse_wrap[part_name],
        remesh_postwrap=False,
        enable_feature_octree_refinement=False,
    )
    # Closed part with no hole
    display(scope=prime.ScopeDefinition(model, part_expression=closed_part.name))

```

So model and mesh information is being kept in the plotter itself. I've implemented the `Mesh` class to avoid this, and have a clear separation between meshes and plotting. Issue is that the API needs to change, as information is managed differently. I think this is more PyVista-like:

```python

for part_name in coarse_wrap:
    # Each open part before wrap
    scope = prime.ScopeDefinition(model, part_expression=part_name)
    pl = PrimePlotter()
    pl.plot(model, scope)
    pl.show()
    closed_part = mesh_util.wrap(
        input_parts=part_name,
        max_size=coarse_wrap[part_name],
        remesh_postwrap=False,
        enable_feature_octree_refinement=False,
    )
    # Closed part with no hole
    scope = prime.ScopeDefinition(model, part_expression=closed_part.name)

    pl = PrimePlotter()
    pl.show(model, scope)
```

Note that users can also just initialize the plotter and use the show method with the model and the scope directly. The mesh information is kept nicely in the model object rather than in the plotter, so you can use the plotter for other models too if needed, for example. 

I could implement something like this tha would behave as the previous API but I think it's kind of messy:

```python
def display(model, scope):
    PrimePlotter().show(model, scope)
```

What do you think?

2024-05-31 12:36 UTC, RobPasMue commented on doc/source/user_guide/graphics.rst
> +    >>> display.show()
I prefer your implementation to be honest - I am not a super fan of the plotter keeping relevant information that can get outdated so your implementation solves that issue. However, I believe it will also be up to @ansys/pyprimemesh-maintainers @ansys/pyprimemesh-admins to decide. =)

2024-05-31 12:37 UTC, RobPasMue commented on doc/source/user_guide/graphics.rst
> +    >>> display.show()
Or @ansys/pyprimemesh to be broad

2024-05-31 12:48 UTC, RobPasMue commented on src/ansys/meshing/prime/core/mesh.py
>          """Update the polydata object of the mesh.
Watchout... I'm not sure what happens with Python 3.9 with ``list``.. Typing changed a lot from 3.9 to 3.10. You might have to import the old ``List`` style from typing

2024-06-04 13:13 UTC, waltersma commented on src/ansys/meshing/prime/graphics/plotter.py
> +from ansys.meshing.prime.graphics.widgets.toogle_edges import ToogleEdges
Hi @AlejandroFernandezLuces, multiple references to toogle, I believe this might be intended to be toggle? Thanks

2024-06-06 10:54 UTC, RobPasMue approved these changes
LGTM!

2024-06-12 15:54 UTC, PipKat commented on examples/other/elbow_trame.py
>  # pop a browser window with the visualizer open.
```suggestion
# ``use_trame`=True``. When the ``display()`` function executes, it
# opens the visualizer in a browser window.
```

2024-06-12 15:56 UTC, PipKat commented on examples/other/pipe_tee.py
>  # part as you would get after you imported from CAD.
```suggestion
# Read from the file, which is an unmeshed part
# like you would get after you imported from a CAD file.
```

2024-06-12 15:57 UTC, PipKat commented on examples/other/pipe_tee.py
>  # prism layers that were specified by the Prism control.
```suggestion
# Display mesh without unwanted edge zonelets. You can clearly see the
# prism layers that were specified by the Prism control.
```
In "Prism control," use double backticks around "Prism if it is a code entity.

2024-06-12 15:58 UTC, PipKat commented on examples/other/pipe_tee.py
>  # Write a cas file for use in the Fluent solver
```suggestion
# Write a CAS file for use in the Fluent solver
```

2024-06-12 15:58 UTC, PipKat commented on src/ansys/meshing/prime/core/mesh.py
> +    """Contains the information of the mesh we want to display.
```suggestion
    """Contains the mesh information to display.
```

2024-06-12 16:00 UTC, PipKat commented on src/ansys/meshing/prime/core/mesh.py
> +        Type of mesh to display.
```suggestion
    id : int, default: 0
        ID of the mesh.
    part_id : int, default: 0
        ID of the part.
    part_name : str, default: None
        Name of the part.
    zone_id : int, default: 0
        ID of the zone.
    zone_name : str, default: None
        Name of the zone.
    display_mesh_type : DisplayMeshType, default: FACEZONELET
        Type of mesh to display.
```

2024-06-12 16:00 UTC, PipKat commented on src/ansys/meshing/prime/core/mesh.py
> +        """Initialize display mesh info."""
```suggestion
        """Initialize display mesh information."""
```

2024-06-12 16:01 UTC, PipKat commented on src/ansys/meshing/prime/core/mesh.py
> +    """Process the mesh for visualization in the GUI.
```suggestion
    """Processes the mesh for visualization in the GUI.
```
Class descriptions start with verbs ending in "s" or "es"

2024-06-12 16:02 UTC, PipKat commented on src/ansys/meshing/prime/core/mesh.py
> +        """Return the model."""
```suggestion
        """Model."""
```
Properties are described as nouns.

2024-06-12 16:06 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +        Whether to allow picking or not, by default True.
```suggestion
    use_trame : Optional[bool], default: None
        Whether to use Trame.
    allow_picking : Optional[bool], default: True.
        Whether to allow picking.
```
I thought you were specifying the default value after the data type. Sorry if I'm remembering wrong! You can see that using this method often cuts down on words.

2024-06-12 16:08 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +        """Get the info actor map for picked info widget.
```suggestion
        """Get the info actor map for the selected information widget.
```
We should spell out words in descriptions.

2024-06-12 16:08 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +            Info actor map.
```suggestion
            Information actor map.
```

2024-06-12 16:08 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +        """Set the info actor map for picked info widget.
```suggestion
        """Set the info actor map for the selected information widget.
```

2024-06-12 16:09 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +            Info actor map.
```suggestion
            Information actor map.
```

2024-06-12 16:09 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +            Mesh info that generates an appropriate color.
```suggestion
            Mesh information that generates an appropriate color.
```

2024-06-12 16:10 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +            Scope to show if any, by default None
```suggestion
        scope : prime.ScopeDefinition, default: None
            Scope to show, if any.
```

2024-06-12 16:11 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +            Regular expression with the desired name or names you want to include in the plotter.
```suggestion
            List of objects to plot.
        name_filter : str, default: None
            Regular expression with the desired name or names to include in the plotter.
```

2024-06-12 16:14 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +            Additional plotting options the selected backend accepts.
```suggestion
        plottable_object : Any, default: None
            Object to show.
        screenshot : str, default: None
            Path to save a screenshot to.
        name_filter : bool, default: None
            Whether to filter the object.
        plotting_options : dict, default: None
            Additional plotting options that the selected backend accepts.
```
Is ``name_filter`` really a Boolean? It seems like it would be string?

2024-06-12 16:15 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +        Whether to use the Trame visualizer. The default is ``False``.
```suggestion
    use_trame : bool, default: False
        Whether to use the Trame visualizer.```

2024-06-12 16:18 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +            "DeprecationWarning: Graphics module is deprecated. Use `PrimePlotter` instead."
```suggestion
            "DeprecationWarning: The `Graphics` class is deprecated. Use the `PrimePlotter` class instead."
```

2024-06-12 16:19 UTC, PipKat commented on src/ansys/meshing/prime/graphics/plotter.py
> +            Scope of the parts. The default is ``None``.
```suggestion
        parts : Any, default: None
            Parts to show. 
        update : bool, default: True
            Whether to update the display.
        spline : bool, default: False
            Whether to use splines.
        scope : prime.ScopeDefinition, default: None
            Scope of the parts.
```

2024-06-12 16:20 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/color_by_type.py
> +    """Initialize the color by type button widget.
```suggestion
    """Initializes the color by the type button widget.
```

2024-06-12 16:20 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/color_by_type.py
> +    based on the zone, zonelet or part.
```suggestion
    This widget lets you change the color of the mesh
    based on the zone, zonelet, or part.
```

2024-06-12 16:21 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/color_by_type.py
> +            Color type to use, by default ColorByType.ZONE.
```suggestion
        color_type : ColorByType, default: ColorByType.ZONE
            Color type to use.
```

2024-06-12 16:22 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/color_by_type.py
> +            Mesh info that generates an appropriate color.
```suggestion
            Mesh information that generates an appropriate color.
```

2024-06-12 16:22 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/hide_picked.py
> +    """Initialize the hide picked button widget.
```suggestion
    """Initializes the hide picked button widget.
```

2024-06-12 16:23 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/hide_picked.py
> +        Plotter where to apply this widget.
```suggestion
        Plotter to apply this widget to.
```

2024-06-12 16:24 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +    This widget allows the user to get information about the picked mesh objects.
```suggestion
    """Initializes the picked information button widget.

    This widget lets you get information about the picked mesh objects.
```

2024-06-12 16:24 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +        Plotter where to apply this widget.
```suggestion
        Plotter to apply this widget to.
```

2024-06-12 16:25 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +        """Return the information message for the selected mesh object.
```suggestion
        """Get the information message for the selected mesh object.
```

2024-06-12 16:25 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +            The mesh info object to print.
```suggestion
            Mesh information object to print.
```

2024-06-12 16:25 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +        """Define callback function for the button widget.
```suggestion
        """Define the callback function for the button widget.
```

2024-06-12 16:25 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +        state : bool
```suggestion
        state : bool, default: None
```

2024-06-12 16:26 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/toggle_edges.py
> +    """Toggle the edges of the mesh objects.
```suggestion
    """Toggles the edges of the mesh objects.
```

2024-06-12 16:26 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/toggle_edges.py
> +        Plotter where to apply this widget.
```suggestion
        Plotter to apply this widget to.
```

2024-06-12 16:28 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +            State of the button widget.
Not sure I or a user would understand what Boolean value to specify. Can the description be more comprehensive? Same for other occurrences of the ``state`` parameter.

2024-06-13 07:23 UTC, AlejandroFernandezLuces commented on src/ansys/meshing/prime/graphics/plotter.py
> +        Whether to allow picking or not, by default True.
I think we are not consistent with this across PyAnsys libraries. I agree with you, we can use this method for this repo.

2024-06-13 07:29 UTC, AlejandroFernandezLuces commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +            State of the button widget.
Honestly, I documented this function, as well as all other `callback` methods so pre-commit wouldn't complain. These functions are not meant to be used by anyone directly. This function is called when the user presses a button in the GUI. So I don't think it's worth explaining this in detail. This `state` is really the internal state of the button, whether it is activated or not. 

If you think it still is worth to add more detail to this, let me know

2024-06-13 07:47 UTC, AlejandroFernandezLuces commented on src/ansys/meshing/prime/graphics/plotter.py
> +            Additional plotting options the selected backend accepts.
This is a mistake, it is indeed an string.

2024-06-13 13:31 UTC, PipKat commented on src/ansys/meshing/prime/graphics/widgets/picked_info.py
> +            State of the button widget.
@AlejandroFernandezLuces 
Based on your explanation, can we change the description to this:

Whether the button widget is activated.

That would make the format consistent with our other Boolean descriptions.

2024-07-16 12:16 UTC, waltersma submitted a review, later dismissed

2024-07-22 09:54 UTC, AlejandroFernandezLuces commented
@waltersma I've fixed the issues I've found in the examples, and added interactive examples in the documentation. If you want to check out the rendered examples, you can download the documentation from the artifacts and run this:

```bash
python -m http.server -b localhost 8080
```

[video.webm](https://github.com/user-attachments/assets/d1966c81-5741-474b-8b7a-89a0a7000ac7)


If you are worried about the buttons appearing in the static scene, it will be fixed in the next release of the visualization tool.

2024-07-22 10:05 UTC, waltersma commented
> @waltersma I've fixed the issues I've found in the examples, and added interactive examples in the documentation. If you want to check out the rendered examples, you can download the documentation from the artifacts and run this:
> 
> ```shell
> python -m http.server -b localhost 8080
> ```
> 
>  video.webm 
> If you are worried about the buttons appearing in the static scene, it will be fixed in the next release of the visualization tool.

This looks good to me!

2024-07-22 10:06 UTC, waltersma approved these changes

2024-07-22 10:28 UTC, AlejandroFernandezLuces commented
Thanks everyone for your reviews 😄

2024-07-22 10:28 UTC, merged